language: java
addons:
  sonarcloud:
    organization: "mrn73130"
    token:
      secure: $tp2

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.projectKey=MRN73130_sample-application-students
  - echo "$dockerhubpassword" | docker login -u "$dockerhublogin" --password-stdin

  - docker build -t http sample-application-http-api-server
  - docker build -t db sample-application-db-changelog-job
  - docker tag http $dockerhublogin/tp2:http
  - docker tag db $dockerhublogin/tp2:db
  - docker push $dockerhublogin/tp2:http
  - docker push $dockerhublogin/tp2:db

cache:
  directories:
    - $HOME/.m2

