language: java
script:
  - mvn clean verify
  - mvn package -DskipTests

  - docker build -t http sample-application-http-api-server
  - docker build -t db sample-application-db-changelog-job

cache:
  directories:
    - $HOME/.m2
